import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from './components/Navigation'
import { StrictMode } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Multiapps | Make your life easier</title>
      </head>
      <body className={inter.className}>
        <Navigation />
        <StrictMode>
          {children}
        </StrictMode>
      </body>
    </html>
  )
}
